version: "3.4"

services:
  deliveggie-gateway-api:
    image: deliveggie-gateway-api
    container_name: "deliveggie-gateway-api"
    build:
      context: .
      dockerfile: src/Gateway/DeliVeggie.GatewayAPI/Dockerfile
    environment:
      ConnectionStrings__RabbitMqConnectionString: host=rabbitmq:5672;publisherConfirms=true;timeout=10
    ports:
      - 5062:80
      - 5063:80
    depends_on:
      - rabbitmq
  deliveggie-product-service:
    image: deliveggie-product-service
    container_name: "deliveggie-product-service"
    build:
      context: .
      dockerfile: src/Services/DeliVeggie.Product.Service/Dockerfile
    environment:
      ConnectionStrings__MongoConnectionString: mongodb://mongo/deli-veggie
      ConnectionStrings__RabbitMqConnectionString: host=rabbitmq:5672;publisherConfirms=true;timeout=10
    depends_on:
      - rabbitmq
      - mongo

  deliveggie-product-ui:
    image: deliveggie-product-ui
    container_name: "deliveggie-product-ui"
    build:
      context: .
      dockerfile: src/Presentation/DeliVeggieUI/Dockerfile
    ports:
      - 5070:80
    depends_on:
      - deliveggie-gateway-api
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "deliveggie-products-rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
  mongo:
    image: mongo
    restart: always
    container_name: "deliveggie-mongodb"
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    container_name: "deliveggie-mongodb-ui"
    restart: always
    ports:
      - 27027:8081
